org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8 -XX:+UseZGC -XX:+UnlockExperimentalVMOptions -XX:ZAllocationSpikeTolerance=5
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
org.gradle.java.installations.auto-download=true
android.suppressUnsupportedCompileSdk=35,36,37

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

# Android Studio Gradle JDK: unngå GRADLE_LOCAL_JAVA_HOME makro feil
# Bruker JBR 21 lokalt (som allerede er lastet ned).
org.gradle.java.home=C:/Users/tlarsen/.jdks/jbr-21.0.11

