org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8 -XX:+UseZGC -XX:+UnlockExperimentalVMOptions -XX:ZAllocationSpikeTolerance=5
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
org.gradle.java.installations.auto-download=true
android.suppressUnsupportedCompileSdk=35,36,37
